//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	config "github.com/gardener/gardener-extension-shoot-networking-filter/pkg/apis/config"
	apisconfig "github.com/gardener/gardener/extensions/pkg/apis/config"
	configv1alpha1 "github.com/gardener/gardener/extensions/pkg/apis/config/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Configuration)(nil), (*config.Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Configuration_To_config_Configuration(a.(*Configuration), b.(*config.Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Configuration)(nil), (*Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Configuration_To_v1alpha1_Configuration(a.(*config.Configuration), b.(*Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DownloaderConfig)(nil), (*config.DownloaderConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DownloaderConfig_To_config_DownloaderConfig(a.(*DownloaderConfig), b.(*config.DownloaderConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.DownloaderConfig)(nil), (*DownloaderConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_DownloaderConfig_To_v1alpha1_DownloaderConfig(a.(*config.DownloaderConfig), b.(*DownloaderConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EgressFilter)(nil), (*config.EgressFilter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EgressFilter_To_config_EgressFilter(a.(*EgressFilter), b.(*config.EgressFilter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.EgressFilter)(nil), (*EgressFilter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_EgressFilter_To_v1alpha1_EgressFilter(a.(*config.EgressFilter), b.(*EgressFilter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EnsureConnectivity)(nil), (*config.EnsureConnectivity)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EnsureConnectivity_To_config_EnsureConnectivity(a.(*EnsureConnectivity), b.(*config.EnsureConnectivity), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.EnsureConnectivity)(nil), (*EnsureConnectivity)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_EnsureConnectivity_To_v1alpha1_EnsureConnectivity(a.(*config.EnsureConnectivity), b.(*EnsureConnectivity), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Filter)(nil), (*config.Filter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Filter_To_config_Filter(a.(*Filter), b.(*config.Filter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Filter)(nil), (*Filter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Filter_To_v1alpha1_Filter(a.(*config.Filter), b.(*Filter), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Configuration_To_config_Configuration(in *Configuration, out *config.Configuration, s conversion.Scope) error {
	out.EgressFilter = (*config.EgressFilter)(unsafe.Pointer(in.EgressFilter))
	out.HealthCheckConfig = (*apisconfig.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	return nil
}

// Convert_v1alpha1_Configuration_To_config_Configuration is an autogenerated conversion function.
func Convert_v1alpha1_Configuration_To_config_Configuration(in *Configuration, out *config.Configuration, s conversion.Scope) error {
	return autoConvert_v1alpha1_Configuration_To_config_Configuration(in, out, s)
}

func autoConvert_config_Configuration_To_v1alpha1_Configuration(in *config.Configuration, out *Configuration, s conversion.Scope) error {
	out.EgressFilter = (*EgressFilter)(unsafe.Pointer(in.EgressFilter))
	out.HealthCheckConfig = (*configv1alpha1.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	return nil
}

// Convert_config_Configuration_To_v1alpha1_Configuration is an autogenerated conversion function.
func Convert_config_Configuration_To_v1alpha1_Configuration(in *config.Configuration, out *Configuration, s conversion.Scope) error {
	return autoConvert_config_Configuration_To_v1alpha1_Configuration(in, out, s)
}

func autoConvert_v1alpha1_DownloaderConfig_To_config_DownloaderConfig(in *DownloaderConfig, out *config.DownloaderConfig, s conversion.Scope) error {
	out.Endpoint = in.Endpoint
	out.OAuth2Endpoint = (*string)(unsafe.Pointer(in.OAuth2Endpoint))
	out.RefreshPeriod = (*v1.Duration)(unsafe.Pointer(in.RefreshPeriod))
	return nil
}

// Convert_v1alpha1_DownloaderConfig_To_config_DownloaderConfig is an autogenerated conversion function.
func Convert_v1alpha1_DownloaderConfig_To_config_DownloaderConfig(in *DownloaderConfig, out *config.DownloaderConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_DownloaderConfig_To_config_DownloaderConfig(in, out, s)
}

func autoConvert_config_DownloaderConfig_To_v1alpha1_DownloaderConfig(in *config.DownloaderConfig, out *DownloaderConfig, s conversion.Scope) error {
	out.Endpoint = in.Endpoint
	out.OAuth2Endpoint = (*string)(unsafe.Pointer(in.OAuth2Endpoint))
	out.RefreshPeriod = (*v1.Duration)(unsafe.Pointer(in.RefreshPeriod))
	return nil
}

// Convert_config_DownloaderConfig_To_v1alpha1_DownloaderConfig is an autogenerated conversion function.
func Convert_config_DownloaderConfig_To_v1alpha1_DownloaderConfig(in *config.DownloaderConfig, out *DownloaderConfig, s conversion.Scope) error {
	return autoConvert_config_DownloaderConfig_To_v1alpha1_DownloaderConfig(in, out, s)
}

func autoConvert_v1alpha1_EgressFilter_To_config_EgressFilter(in *EgressFilter, out *config.EgressFilter, s conversion.Scope) error {
	out.BlackholingEnabled = in.BlackholingEnabled
	out.FilterListProviderType = config.FilterListProviderType(in.FilterListProviderType)
	out.StaticFilterList = *(*[]config.Filter)(unsafe.Pointer(&in.StaticFilterList))
	out.DownloaderConfig = (*config.DownloaderConfig)(unsafe.Pointer(in.DownloaderConfig))
	out.EnsureConnectivity = (*config.EnsureConnectivity)(unsafe.Pointer(in.EnsureConnectivity))
	out.PSPDisabled = (*bool)(unsafe.Pointer(in.PSPDisabled))
	return nil
}

// Convert_v1alpha1_EgressFilter_To_config_EgressFilter is an autogenerated conversion function.
func Convert_v1alpha1_EgressFilter_To_config_EgressFilter(in *EgressFilter, out *config.EgressFilter, s conversion.Scope) error {
	return autoConvert_v1alpha1_EgressFilter_To_config_EgressFilter(in, out, s)
}

func autoConvert_config_EgressFilter_To_v1alpha1_EgressFilter(in *config.EgressFilter, out *EgressFilter, s conversion.Scope) error {
	out.BlackholingEnabled = in.BlackholingEnabled
	out.FilterListProviderType = FilterListProviderType(in.FilterListProviderType)
	out.StaticFilterList = *(*[]Filter)(unsafe.Pointer(&in.StaticFilterList))
	out.DownloaderConfig = (*DownloaderConfig)(unsafe.Pointer(in.DownloaderConfig))
	out.EnsureConnectivity = (*EnsureConnectivity)(unsafe.Pointer(in.EnsureConnectivity))
	out.PSPDisabled = (*bool)(unsafe.Pointer(in.PSPDisabled))
	return nil
}

// Convert_config_EgressFilter_To_v1alpha1_EgressFilter is an autogenerated conversion function.
func Convert_config_EgressFilter_To_v1alpha1_EgressFilter(in *config.EgressFilter, out *EgressFilter, s conversion.Scope) error {
	return autoConvert_config_EgressFilter_To_v1alpha1_EgressFilter(in, out, s)
}

func autoConvert_v1alpha1_EnsureConnectivity_To_config_EnsureConnectivity(in *EnsureConnectivity, out *config.EnsureConnectivity, s conversion.Scope) error {
	out.SeedNamespaces = *(*[]string)(unsafe.Pointer(&in.SeedNamespaces))
	return nil
}

// Convert_v1alpha1_EnsureConnectivity_To_config_EnsureConnectivity is an autogenerated conversion function.
func Convert_v1alpha1_EnsureConnectivity_To_config_EnsureConnectivity(in *EnsureConnectivity, out *config.EnsureConnectivity, s conversion.Scope) error {
	return autoConvert_v1alpha1_EnsureConnectivity_To_config_EnsureConnectivity(in, out, s)
}

func autoConvert_config_EnsureConnectivity_To_v1alpha1_EnsureConnectivity(in *config.EnsureConnectivity, out *EnsureConnectivity, s conversion.Scope) error {
	out.SeedNamespaces = *(*[]string)(unsafe.Pointer(&in.SeedNamespaces))
	return nil
}

// Convert_config_EnsureConnectivity_To_v1alpha1_EnsureConnectivity is an autogenerated conversion function.
func Convert_config_EnsureConnectivity_To_v1alpha1_EnsureConnectivity(in *config.EnsureConnectivity, out *EnsureConnectivity, s conversion.Scope) error {
	return autoConvert_config_EnsureConnectivity_To_v1alpha1_EnsureConnectivity(in, out, s)
}

func autoConvert_v1alpha1_Filter_To_config_Filter(in *Filter, out *config.Filter, s conversion.Scope) error {
	out.Network = in.Network
	out.Policy = config.Policy(in.Policy)
	return nil
}

// Convert_v1alpha1_Filter_To_config_Filter is an autogenerated conversion function.
func Convert_v1alpha1_Filter_To_config_Filter(in *Filter, out *config.Filter, s conversion.Scope) error {
	return autoConvert_v1alpha1_Filter_To_config_Filter(in, out, s)
}

func autoConvert_config_Filter_To_v1alpha1_Filter(in *config.Filter, out *Filter, s conversion.Scope) error {
	out.Network = in.Network
	out.Policy = Policy(in.Policy)
	return nil
}

// Convert_config_Filter_To_v1alpha1_Filter is an autogenerated conversion function.
func Convert_config_Filter_To_v1alpha1_Filter(in *config.Filter, out *Filter, s conversion.Scope) error {
	return autoConvert_config_Filter_To_v1alpha1_Filter(in, out, s)
}
