apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: shoot-networking-filter
build:
  tagPolicy:
    customTemplate:
      template: "{{.version}}-{{.sha}}"
      components:
        - name: version
          envTemplate:
            template: "{{.EXTENSION_VERSION}}"
        - name: sha
          gitCommit:
            variant: AbbrevCommitSha
  artifacts:
    - image: local-skaffold/gardener-extension-shoot-networking-filter
      ko:
        dependencies:
          paths:
            - cmd/gardener-extension-shoot-networking-filter/
            - imagevector/images.yaml
            - pkg/apis/config/
            - pkg/apis/config/v1alpha1/
            - pkg/controller/config/
            - pkg/controller/healthcheck/
            - pkg/controller/lifecycle/
            - VERSION
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/gardener-extension-shoot-networking-filter/

  insecureRegistries:
    - garden.local.gardener.cloud:5001
manifests:
  kustomize:
    paths:
      - local-setup
deploy:
  # --server-side apply is a workaround for https://github.com/gardener/gardener/issues/10267.
  # kubectl apply attempts a strategic merge patch which fails for a ControllerDeployment.
  # For more details, see https://github.com/gardener/gardener/issues/10267.
  #
  # TODO: Switch back to "kubectl: {}" when the above issue is resolved.
  kubectl:
    flags:
      apply:
        - --server-side
        - --force-conflicts
resourceSelector:
  # instruct skaffold to inject the built image reference into the image field in our ControllerDeployment
  allow:
    - groupKind: ControllerDeployment.core.gardener.cloud
      image:
        - .helm.values.image.ref