image:
  repository: ghcr.io/stackitcloud/gardener-extension-shoot-network-filter-admission
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1
healthPort: 8081
resources: {}
vpa:
  enabled: true
  resourcePolicy:
    minAllowed:
      cpu: 50m
      memory: 64Mi
  updatePolicy:
    updateMode: "Auto"
webhookConfig:
  serverPort: 10250
# Kubeconfig to the target cluster. In-cluster configuration will be used if not specified.
kubeconfig:

# projectedKubeconfig:
#   baseMountPath: /var/run/secrets/gardener.cloud
#   genericKubeconfigSecretName: generic-token-kubeconfig
#   tokenSecretName: access-network-filter-admission

service:
  topologyAwareRouting:
    enabled: false

gardener:
  virtualCluster:
    enabled: true
    serviceAccount: {}
#     name: gardener-extension-shoot-network-filter-admission
#     namespace: kube-system
  runtimeCluster: {}
#   priorityClassName: gardener-garden-system-400
